### ISSUE TITLE
Folders get created unnecessarily for generated WebPs

### ISSUE THREAD

**Issue by vibin** [somerandomdude/grunt-webp#4]
Here's the snippet from my Grunt.js

``` webp:{
    dist:{
      files: [{
        expand: true, 
        cwd: 'src/img',
        src:['*.jpg'],
        dest:'src/img/',
        ext:'.jpg.webp'
        }],
    },
      options:{
        quality:85,
    },
  },
```

When ever I run grunt webp, folders with name as `[filename].jpg.webp` get created and the actual .webp files reside inside them. 

I don't want this to happen. I want my actual webp files to have the name `[filename].jpg.webp` and no extra folders should be created (as the `dest` is already mentioned).

**Comment by somerandomdude** [comment]
I'll look into this. Thanks!

P.J.

**Comment by vibin** [comment]
Any progress?

I can see that this line in the webp.js file is creating folders. But I'm a beginner at Javascript stuff, so not really sure.

```
grunt.file.mkdir(dest);
```

**Comment by somerandomdude** [comment]
Not yet. It's on my list of things to do, but I haven't had time to look at it yet.
P.J.

**Comment by wiktor-k** [comment]
As far as I can see the bug exists in version 0.0.1 but is fixed in 0.0.2. The problem is 0.0.2 is not in npm repository so people by default download the buggy 0.0.1 release.

**Comment by TonySpegel** [comment]
As far as I can tell I have version "grunt-webp": "0.0.4" and it still creates unnecessary folders:

```
src: '_source_images/*.jpg',
dest: 'webp_images/'
```

creates _source_images IN webp_images wich in fact i don't want it to do.

Also that's over a year old... and still not fixed? ok..
